### ISSUE TITLE
scaler error in CSS/Phoebus (Feb 2024 VM)

### ISSUE THREAD

**Issue by lcgallington** [BCDA-APS/epics-bluesky-vm#35]
When I try to look at the scalers on the detectors tab in CSS (Feb 2024 VM), I get an error.  Output from the error log and screenshots below.

```
2024-02-12 13:10:12 WARNING [org.csstudio.display.builder.runtime] Error handling Scaler 1 (16 ch)
java.lang.Exception: Cannot load 'scaler16.opi' (parent: '/home/apsu/epics_screens/synApps/bob/ioc_detectors.bob')
	at org.csstudio.display.builder.model.persist.ModelLoader.resolveAndLoadModel(ModelLoader.java:65)
	at org.csstudio.display.builder.runtime.ActionUtil.openDisplay(ActionUtil.java:102)
	at org.csstudio.display.builder.runtime.ActionUtil.lambda$handleAction$0(ActionUtil.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException: /home/apsu/epics_screens/synApps/bob/scaler16.opi (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at org.csstudio.display.builder.model.util.ModelResourceUtil.openResourceStream(ModelResourceUtil.java:466)
	at org.csstudio.display.builder.model.persist.ModelLoader.loadModel(ModelLoader.java:77)
	at org.csstudio.display.builder.model.persist.ModelLoader.resolveAndLoadModel(ModelLoader.java:47)
	... 5 more
```

![image](https://github.com/BCDA-APS/epics-bluesky-vm/assets/62352329/d67a3d04-0813-4458-a5ec-3e8cd36fec71)

![image](https://github.com/BCDA-APS/epics-bluesky-vm/assets/62352329/d37334f2-71d4-4ae5-8cca-507e92146025)

![image](https://github.com/BCDA-APS/epics-bluesky-vm/assets/62352329/276b2e25-b08f-4bbd-96fa-2888edf58a21)

**Comment by lcgallington** [comment]
To pin things down a bit, on the ioc_detectors page, the following items give an error:
1. scaler 1, scaler 2, and scaler 3 no matter how many channels are selected
2. SIS3820 (both options in dropdown)
3. quadEM: Quad Electrometer Ch.1, '' Ch. 2, '' Ch. 3, '' Ch. 4. '' MCAs [however vertival feedback and horizontal feedback options launch fine!)
All other options launch without that popup message.

edit 1 to remove unintentional links to other issues.

edit 2: after more digging, it looks like the bob files for all these detectors are missing from the bob subdirectory, but there are opi files that correspond to these quantities in the opi subdirectory except for quadEM.  If I stick the relevant opis in the bob directory, the error goes away.

**Comment by prjemian** [comment]
Thanks for the report.  Good news, the missing screens have been found **and** they are in your VM.  Bad news, they are in the wrong directory!

```bash
~/epics_screens/synApps_6_2_1/adl/scaler16_full.bob
~/epics_screens/synApps_6_2_1/adl/scaler16_full_calc.bob
~/epics_screens/synApps_6_2_1/adl/scaler16_more.bob
~/epics_screens/synApps_6_2_1/adl/scaler16m.bob
~/epics_screens/synApps_6_2_1/adl/scaler16m_full.bob
~/epics_screens/synApps_6_2_1/adl/scaler16m_full_calc.bob
~/epics_screens/synApps_6_2_1/adl/scaler16m_more.bob
```

Use this bash command to move them to the correct place.  You _might_ need to restart phoebus (on my workstation, restart was not necessary).

```bash
mv ~/epics_screens/synApps_6_2_1/{adl,bob}/scaler16.bob
mv ~/epics_screens/synApps_6_2_1/{adl,bob}/scaler16_full.bob
mv ~/epics_screens/synApps_6_2_1/{adl,bob}/scaler16_full_calc.bob
mv ~/epics_screens/synApps_6_2_1/{adl,bob}/scaler16_more.bob
mv ~/epics_screens/synApps_6_2_1/{adl,bob}/scaler16m.bob
mv ~/epics_screens/synApps_6_2_1/{adl,bob}/scaler16m_full.bob
mv ~/epics_screens/synApps_6_2_1/{adl,bob}/scaler16m_full_calc.bob
mv ~/epics_screens/synApps_6_2_1/{adl,bob}/scaler16m_more.bob
```

**Comment by lcgallington** [comment]
Seems like that fixed the problem with the scalers.  I checked the adl directory for the quadEM and SIS3820 bobs, but didn’t see them.  I don’t think I need those for now though.

--
Leighanne C. Gallington, Ph.D.
Assistant Physicist
Advanced Photon Source (X-ray Science Division)
Argonne National Laboratory
Argonne, IL  60439
***@***.***

**Comment by prjemian** [comment]
Found more `.bob` screens in the `.../adl/` directory.  This moves any and all of them:

```bash
mv ~/epics_screens/synApps_6_2_1/adl/*.bob ~/epics_screens/synApps_6_2_1/bob/
```
